const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const ChatbotUserSchema = new mongoose.Schema({
  mobile: { type: String, unique: true },
  full_name: String,
  personal_email: String,
  pan_number: String,
  monthly_income: Number,
  dob: String,
  gender: String,
  marital_status: String,
  spouse_name: String,
  residence_type: String,
  address_line1: String,
  address_line2: String,
  landmark: String,
  pincode: String,
  employment_type: String,
  salary_mode: String,
  salary_date: String,
  loan_amount: Number,
  loan_tenure: Number,
  loan_purpose: String,
  work_mode: String,
  company_name: String,
  company_type: String,
  department: String,
  designation: String,
  official_email: String,
  emp_since: String,
  office_address1: String,
  office_address2: String,
  office_pincode: String,
  account_name: String,
  bank_name: String,
  branch_name: String,
  account_number: String,
  ifsc_code: String,
  ref_no: String,
  application_status: { type: String, enum: ['incomplete', 'submitted', 'under_review', 'approved', 'rejected'], default: 'incomplete' },
}, { timestamps: true });

module.exports = mongoose.model('ChatbotUser', ChatbotUserSchema);
